### ISSUE TITLE
Repository description incorrectly describes this sketch as a "library"

### ISSUE THREAD

**Issue by per1234** [Seeed-Studio/Light_Sensor#3]
From this repository's GitHub repository description:
>Seeed Light Sensor library

But in fact this is not a library. It's a sketch. This will cause confusion for the users regarding how to install and use this code and when they install it as a library it causes the Arduino IDE to display an "Invalid library found" warning on every compilation.

See: https://github.com/MediaTek-Labs/linkit-7697-peripheral-drivers-for-arduino/issues/1

![image](https://user-images.githubusercontent.com/8572152/179443293-969290fa-4555-4bea-9865-7b9bb77312e1.png)

**Comment by baorepo** [comment]
Done

**Comment by per1234** [comment]
Hi @baorepo. Unfortunately it is not done.

Look under the "About" section of the repository home page:

![image](https://github.com/user-attachments/assets/75395a7d-e302-4f42-a677-2bff25be9705)

Please either correct the description immediately, or else reopen this issue so that the maintainers can effectively track the task of fixing it.

**Comment by Lesords** [comment]
Okay, I've corrected it.
